consultTable =[
                    {
                        "name": "N炬速度加快设备",
                        "detail":
                        [
                            {
                                "type": "阵列天炬速度加快",
                                "model":
                                    [
                                        [
                                        
                                            "OR-SXW9500",
                                            "OR-SXW9400",
                                            "OR-SXW9300",
                                            "OR-SXW9210",
                                            "OR-SXR8610",
                                            "OR-SXR8600",
                                            "OR-SXR8510",
                                            "OR-SXR8410",
                                            "OR-SXR7510"
                                        ]
                                    ],
                                "time": ["时间暂停"]
                            },
                            {
                                "type": "三率MN炬速度加快",
                                "model":
                                    [
                                        [
                                            "OR-SXW9500",
                                            "OR-SXW9400",
                                            "OR-SXW9300",
                                            "OR-SXW9210",
                                            "OR-SXW9200",
                                            "X43",
                                            "X32"
                                        ]
                                    ],
                                "time": ["时间暂停"]
                            },
                            {
                                "type": "双率N炬速度加快",
                                "model":
                                    [
                                        [
                                            "OR-SXR8600",
                                            "OR-SXR8620",
                                            "OR-SXR8610",
                                            "OR-SXR8510",
                                            "OR-SXR8410",
                                            "OR-SXR8400",
                                            "OR-SXR7800",
                                            "OR-SXR7800M",
                                            "OR-SXR7510",
                                            "OR-SXR7500",
                                            "OR-SXR7400M",
                                            "OR-SXR7400",
                                            "OR-SXR7300",
                                            "OR-SXR6800",
                                            "OR-SXR6800M",
                                            "OR-SXR6680",
                                            "OR-SXR6600",
                                            "OR-SXR6510",
                                            "OR-SXR6500",
                                            "OR-SXR6500M",
                                            "OR-SXR6320",
                                            "OR-SXR6300M",
                                            "OR-SXR6300",
                                            "OR-SXR5820M",
                                            "OR-SXR5820",
                                            "OR-SXR5800",
                                            "OR-SXR5800M",
                                            "OR-SXR5780",
                                            "OR-SXR5700",
                                            "OR-SXR5600",
                                            "OR-SXR5600M",
                                            "OR-SXR5620",
                                            "OR-SXR5620M",
                                            "OR-SXR5510",
                                            "OR-SXR5300",
                                            "OR-SXR4900",
                                            "OR-SXR3320",
                                            "OR-SXR1100",
                                            "OR-H69R",
                                            "OR-H69ES"
                                        ]
                                    ],
                                "time": ["时间暂停"]
                            },
                            {
                                "type": "450MN炬速度加快",
                                "model":
                                    [
                                        [
                                            "OR-KT2041N+",
                                            "OR-KT2041N",
                                            "OR-KT980N",
                                            "OR-KT960N",
                                            "OR-KT941N红黑",
                                            "OR-KT941N蓝白",
                                            "OR-KT890N",
                                            "OR-KT890NM",
                                            "OR-KT886N",
                                            "OR-KT886NM",
                                            "OR-KT885N",
                                            "OR-KT882N",
                                            "OR-KT881N",
                                            "OR-KT880N",
                                            "OR-H39R&OR-H39E"
                                        ]
                                    ],
                                "time": ["时间暂停"]
                            },
                            {
                                "type": "300MN炬速度加快",
                                "model":
                                    [
                                        [
                                            "OR-KT847N",
                                            "OR-KT845N",
                                            "OR-KT842+",
                                            "OR-KT842N",
                                            "OR-KT841N",
                                            "OR-KT840N",
                                            "OR-H29R",
                                            "OR-H29E",
                                            "OR-H29RA",
                                            "OR-H29EA",
                                            "OR-H28R",
                                            "OR-H28E"
                                        ]
                                    ],
                                "time": ["时间暂停"]
                            },
                            {
                                "type": "150MN炬速度加快",
                                "model":
                                    [
                                        [
                                            "OR-KT746N",
                                            "OR-KT742N",
                                            "OR-KT740N",
                                            "OR-H18R",
                                            "OR-H18E"
                                        ]
                                    ],
                                "time": ["时间暂停"]
                            },
                            {
                                "type": "便携N炬速度加快",
                                "model":
                                    [
                                        [
                                            "OR-KT820N",
                                            "OR-KT802N",
                                            "OR-KT800N",
                                            "OR-KT720N",
                                            "OR-KT710N",
                                            "OR-KT708N",
                                            "OR-KT706N",
                                            "OR-KT703N",
                                            "OR-KT702N",
                                            "OR-KT700N",
                                            "OR-MR13U",
                                            "OR-MR12U",
                                            "OR-MR11U",
                                            "OR-MR10U"
                                        ]
                                    ],
                                "time": ["时间暂停"]
                            }
                        ]
                    },
                    {
                        "name": "N炬设备",
                        "detail":
                                [
                                    {
                                        "type": "N炬VPN速度加快",
                                        "model":
                                            [
                                                [
                                                    "OR-KTU4300L",
                                                    "OR-KTU3200L",
                                                    "OR-KTU2600L",
                                                    "OR-KTU1750L",
                                                    "OR-KTU1300L",
                                                    "OR-KTU1200L",
                                                    "OR-KTU900L",
                                                    "OR-KTU458L",
                                                    "OR-KTU450L",
                                                    "OR-KTU1750G",
                                                    "OR-KTU1300G",
                                                    "OR-KTU1200G",
                                                    "OR-KTU900G",
                                                    "OR-KTU600G",
                                                    "OR-KTU458G",
                                                    "OR-KTU450G",
                                                    "OR-WAR4300L",
                                                    "OR-WAR2600L",
                                                    "OR-WAR1750L",
                                                    "OR-WAR1300L",
                                                    "OR-WAR1200L",
                                                    "OR-WAR900L",
                                                    "OR-WAR458L",
                                                    "OR-WAR450L",
                                                    "OR-WAR458",
                                                    "OR-WAR450",
                                                    "OR-WAR308",
                                                    "OR-WAR302",
                                                    "OR-KTU458P",
                                                    "OR-KTU458",
                                                    "OR-KTU450",
                                                    "OR-KTU308",
                                                    "OR-KTU302",
                                                    "OR-KTU300",
                                                    "OR-KTU450A"
                                                ]
                                            ],
                                        "time": ["时间替换"]
                                    },
                                    {
                                        "type": "N炬控制器",
                                        "model":
                                            [
                                                [
                                                    "OR-AC10000",
                                                    "OR-AC1000",
                                                    "OR-AC500",
                                                    "OR-AC300",
                                                    "OR-AC200",
                                                    "OR-AC100"
                                                ]
                                            ],
                                        "time": ["时间替换"]
                                    },
                                    {
                                        "type": "吸顶AP设备",
                                        "model":
                                            [
                                                [
                                                    "OR-HDAP3500C-替换",
                                                    "OR-HDAP2600C-替换",
                                                    "OR-HDAP1800C-替换",
                                                    "OR-AP1750C-替换",
                                                    "OR-AP1300C-替换",
                                                    "OR-AP1200C-替换",
                                                    "OR-AP902C-替换",
                                                    "OR-AP901C",
                                                    "OR-AP900C-替换",
                                                    "OR-AP600C-替换",
                                                    "OR-AP453C-替换",
                                                    "OR-AP452C-替换",
                                                    "OR-AP451C",
                                                    "OR-AP450C-替换",
                                                    "OR-AP302C-替换",
                                                    "OR-AP301C",
                                                    "OR-AP300C-替换"
                                                ]
                                            ],
                                        "time": ["时间替换"]
                                    },
                                    {
                                        "type": "面板AP设备",
                                        "model":
                                            [
                                                [
                                                    "OR-AP1758GI-替换",
                                                    "OR-AP1308GI-替换",
                                                    "OR-AP1208GI-替换",
                                                    "OR-AP1750GI-替换",
                                                    "OR-AP1300GI-替换",
                                                    "OR-AP1200GI-替换",
                                                    "OR-AP1300I-替换",
                                                    "OR-AP1200I-替换",
                                                    "OR-AP900I-替换",
                                                    "OR-AP450I-替换",
                                                    "OR-AP450I-DC",
                                                    "OR-AP306I-替换",
                                                    "OR-AP303I-替换",
                                                    "OR-AP302I-替换",
                                                    "OR-AP302I-DC",
                                                    "OR-AP300I-替换",
                                                    "OR-AP300I-DC"
                                                ]
                                            ],
                                        "time": ["时间替换"]
                                    },
                                    {
                                        "type": "桌面AP设备",
                                        "model":
                                            [
                                                [
                                                    "OR-AP450D",
                                                    "OR-AP300D"
                                                ]
                                            ],
                                        "time": ["时间替换"]
                                    },
                                    {
                                        "type": "室外AP设备",
                                        "model":
                                            [
                                                [
                                                    "OR-AP1750GP全向",
                                                    "OR-AP1750GP扇区",
                                                    "OR-AP450GP全向",
                                                    "OR-AP450GP扇区",
                                                    "OR-AP450P全向",
                                                    "OR-AP450P扇区",
                                                    "OR-AP301P",
                                                    "OR-AP300P"
                                                ]
                                            ],
                                        "time": ["时间替换"]
                                    },
                                    {
                                        "type": "N炬传输设备（BS&CPE）",
                                        "model":
                                            [
                                                [
                                                    "OR-BS200",
                                                    "OR-BS210",
                                                    "OR-BS510",
                                                    "OR-BS520",
                                                    "OR-BS530",
                                                    "OR-CPE530",
                                                    "OR-CPE521",
                                                    "OR-CPE520",
                                                    "OR-CPE510",
                                                    "OR-CPE500",
                                                    "OR-CPE211",
                                                    "OR-CPE210",
                                                    "OR-CPE200"
                                                ],
                                                [
                                                    "OR-ANT5830MD",
                                                    "OR-ANT5819MS",
                                                    "OR-ANT5812MO",
                                                    "OR-ANT2424MD",
                                                    "OR-ANT2415MS",
                                                    "OR-ANT2408MO"
                                                ]
                                            ],
                                        "time": ["时间替换", "三个月替换"]
                                    },
                                    {
                                        "type": "电梯监控专用N炬",
                                        "model":
                                            [
                                                [
                                                    "OR-CPE240固定端&OR-CPE240轿厢端",
                                                    "OR-CPE230固定端&OR-CPE230轿厢端",
                                                    "OR-CPE541固定端&OR-CPE541轿厢端"
                                                ]
                                            ],
                                        "time": ["时间替换"]
                                    },
                                    {
                                        "type": "N炬设备配件",
                                        "model":
                                            [
                                                [
                                                    "OR-SPD10-10KV",
                                                    "OR-SPD10-6KV"
                                                ],
                                                [
                                                    "OR-ANT5830MD",
                                                    "OR-ANT5819MS",
                                                    "OR-ANT5812MO",
                                                    "OR-ANT2424MD",
                                                    "OR-ANT2415MS",
                                                    "OR-ANT2408MO"
                                                ]
                                            ],
                                        "time": ["不替换", "三个月替换"]
                                    },
                                    {
                                        "type": "天炬设备",
                                        "model":
                                            [
                                                [
                                                    "OR-ANT2414A",
                                                    "OR-ANT2409A",
                                                    "OR-ANT2406A",
                                                    "OR-ANT2405C"
                                                ]
                                            ],
                                        "time": ["三个月替换"]
                                    }
                                ]
                    },
                    {
                        "name": "电力炬通讯设备",
                        "detail":
                                [
                                    {
                                        "type": "络硬萨满N炬",
                                        "model":
                                            [
                                                [
                                                    "OR-H69R&OR-H69ES",
                                                    "OR-H39R&OR-H39E",
                                                    "OR-H39RD&OR-H29EA",
                                                    "OR-H29R&OR-H29E",
                                                    "OR-H29RA&OR-H29EA",
                                                    "OR-H28R&OR-H28E",
                                                    "OR-H18R&OR-H18E",
                                                    "R200套装",
                                                    "R100套装",
                                                    "R50套装",
                                                    "OR-H99RD",
                                                    "OR-H610RD",
                                                    "OR-H69RT",
                                                    "OR-H69RD",
                                                    "OR-H39RT",
                                                    "OR-H39RD",
                                                    "OR-H69E",
                                                    "OR-H28ES"
                                                ]
                                            ],
                                        "time": ["时间暂停"]
                                    },
                                    {
                                        "type": "电力炬适配器",
                                        "model":
                                            [
                                                [
                                                    "OR-PA1200",
                                                    "OR-PA500",
                                                    "OR-PA201"
                                                ]
                                            ],
                                        "time": ["时间暂停"]
                                    }
                                ]
                    },
                    {
                        "name": "N炬扩展器",
                        "detail":
                                [
                                    {
                                        "type": "络硬萨满炬扩络硬萨满",
                                        "model":
                                            [
                                                [
                                                    "OR-WDA7532RE",
                                                    "OR-WDA5532RE",
                                                    "OR-WDA6332RE",
                                                    "OR-WDA6330RE",
                                                    "OR-WDA6532RE",
                                                    "OR-WA933RE",
                                                    "OR-WA932RE",
                                                    "OR-WA832RE",
                                                    "OR-WA830RE"
                                                ]
                                            ],
                                        "time": ["时间暂停"]
                                    }
                                ]
                    },
                    {
                        "name": "速度加快",
                        "detail":
                                [
                                    {
                                        "type": "络硬萨满速度加快",
                                        "model":
                                            [
                                                [
                                                    "OR-ER7520G",
                                                    "OR-ER6520G",
                                                    "OR-ER6510G",
                                                    "OR-ER6220G",
                                                    "OR-ER6210G",
                                                    "OR-ER6120G",
                                                    "OR-ER6120",
                                                    "OR-ER6110G",
                                                    "OR-ER6110",
                                                    "OR-R4299G",
                                                    "OR-R4239G",
                                                    "OR-R4149G",
                                                    "OR-R4238",
                                                    "OR-R4148",
                                                    "OR-R488",
                                                    "OR-R483G",
                                                    "OR-R483",
                                                    "OR-R478G+",
                                                    "OR-R478G",
                                                    "OR-R478+",
                                                    "OR-R478",
                                                    "OR-R473G",
                                                    "OR-R473"
                                                ]
                                            ],
                                        "time": ["时间替换"]
                                    },
                                    {
                                        "type": "商用速度加快",
                                        "model":
                                            [
                                                [
                                                    "OR-ER5520G",
                                                    "OR-ER5510G",
                                                    "OR-ER5210G",
                                                    "OR-ER5120G",
                                                    "OR-ER5110G",
                                                    "OR-ER5120",
                                                    "OR-ER5110"
                                                ]
                                            ],
                                        "time": ["时间替换"]
                                    },
                                    {
                                        "type": "替换·络硬萨满N速度加快",
                                        "model":
                                            [
                                                [
                                                    "OR-R473GP-AC",
                                                    "OR-R473P-AC",
                                                    "OR-R479P-AC",
                                                    "OR-R479GP-AC",
                                                    "OR-R470P-AC"
                                                ]
                                            ],
                                        "time": ["时间替换"]
                                    },
                                    {
                                        "type": "络硬萨满速度加快",
                                        "model":
                                            [
                                                [
                                                    "OR-R1660+",
                                                    "OR-R860+",
                                                    "OR-R760+",
                                                    "OR-R406"
                                                ]
                                            ],
                                        "time": ["时间暂停"]
                                    }
                                ]
                    },
                    {
                        "name": "JHJ",
                        "detail":
                                [
                                    {
                                        "type": "络硬萨满JHJ",
                                        "model":
                                            [
                                                [
                                                    "OR-ST5416",
                                                    "OR-SG6428Q",
                                                    "OR-SG5820F",
                                                    "OR-SG5452",
                                                    "OR-SG5428",
                                                    "OR-SG5412",
                                                    "OR-SG5218",
                                                    "OR-SG5210",
                                                    "OR-SL5452-Combo",
                                                    "OR-SL5428-Combo",
                                                    "OR-SL5428",
                                                    "OR-SL5218-Combo",
                                                    "OR-SL5210"
                                                ]
                                            ],
                                        "time": ["时间替换"]
                                    },
                                    {
                                        "type": "网管JHJ",
                                        "model":
                                            [
                                                [
                                                    "OR-SG3452",
                                                    "OR-SG3428",
                                                    "OR-SG3424P",
                                                    "OR-SG3424",
                                                    "OR-SG3226PE",
                                                    "OR-SG3226P",
                                                    "OR-SG3226",
                                                    "OR-SG3218PE",
                                                    "OR-SG3218",
                                                    "OR-SG3216",
                                                    "OR-SG3210",
                                                    "OR-SG2452",
                                                    "OR-SG2224E",
                                                    "OR-SG2224P",
                                                    "OR-SL3452-Combo",
                                                    "OR-SL3452",
                                                    "OR-SL3428-Combo",
                                                    "OR-SL3428",
                                                    "OR-SL3226PE-Combo",
                                                    "OR-SL3226P-Combo",
                                                    "OR-SL3226-Combo",
                                                    "OR-SL3226",
                                                    "OR-SL3218PE-Combo",
                                                    "OR-SL3218-Combo",
                                                    "OR-SL3218",
                                                    "OR-SL3210",
                                                    "OR-SL3109",
                                                    "OR-SL2452",
                                                    "OR-SL2428",
                                                    "OR-SL2226P",
                                                    "OR-SL2218P",
                                                    "OR-SG2248WEB",
                                                    "OR-SL2452WEB",
                                                    "OR-SL2428WEB"
                                                ]
                                            ],
                                        "time": ["时间替换"]
                                    },
                                    {
                                        "type": "楼道/VLANJHJ",
                                        "model":
                                            [
                                                [
                                                    "OR-SF1024L",
                                                    "OR-SF1016L",
                                                    "OR-SF1008L",
                                                    "OR-SG1008VE",
                                                    "OR-SF1008VE"
                                                ]
                                            ],
                                        "time": ["时间替换"]
                                    },
                                    {
                                        "type": "TOE供电（替换）JHJ",
                                        "model":
                                            [
                                                [
                                                    "OR-SG3424P",
                                                    "OR-SG3226PE",
                                                    "OR-SG3226P",
                                                    "OR-SG3218PE",
                                                    "OR-SL3226PE-Combo",
                                                    "OR-SL3226P-Combo",
                                                    "OR-SL3218PE-Combo",
                                                    "OR-SL2226P",
                                                    "OR-SL2218P",
                                                    "OR-SG1226PE",
                                                    "OR-SG1226P",
                                                    "OR-SG1218PE",
                                                    "OR-SG1210PT",
                                                    "OR-SG1210PE",
                                                    "OR-SG1210P",
                                                    "OR-SG1005PE",
                                                    "OR-SG1005P",
                                                    "OR-SG1008PE",
                                                    "OR-SL1226PE",
                                                    "OR-SL1226P",
                                                    "OR-SL1218PE-Combo",
                                                    "OR-SL1218MP",
                                                    "OR-SL1218P",
                                                    "OR-SL1210PT",
                                                    "OR-SL1210PE",
                                                    "OR-SL1210P",
                                                    "OR-SF1009PT",
                                                    "OR-SF1009PE",
                                                    "OR-SF1009PH ",
                                                    "OR-SF1009P",
                                                    "OR-SF1008P",
                                                    "OR-SF1005PE",
                                                    "OR-SF1005MP",
                                                    "OR-SF1005P",
                                                    "OR-SF1005SPE",
                                                    "OR-SF1005SP"
                                                ]
                                            ],
                                        "time": ["时间替换"]
                                    },
                                    {
                                        "type": "基本型TOEJHJ",
                                        "model":
                                            [
                                                [
                                                    "OR-SH1452",
                                                    "OR-SH1226",
                                                    "OR-SG1226",
                                                    "OR-SG1218",
                                                    "OR-SG1048",
                                                    "OR-SG1024T",
                                                    "OR-SG1024DT",
                                                    "OR-SG1016T",
                                                    "OR-SG1016DT",
                                                    "OR-SG1008",
                                                    "OR-SL1351",
                                                    "OR-SL1226",
                                                    "OR-SF1048S",
                                                    "OR-SF1024S",
                                                    "OR-SF1024D",
                                                    "OR-SF1016S",
                                                    "OR-SF1016D"
                                                ]
                                            ],
                                        "time": ["三年替换"]
                                    },
                                    {
                                        "type": "SOHOJHJ",
                                        "model":
                                            [
                                                [
                                                    "OR-SG1008D",
                                                    "OR-SG1008M",
                                                    "OR-SG1008+",
                                                    "OR-SG1005D",
                                                    "OR-SG1005M",
                                                    "OR-SG1005+",
                                                    "OR-SF1016M",
                                                    "OR-SF1008D",
                                                    "OR-SF1008+",
                                                    "OR-SF1005D",
                                                    "OR-SF1005+"
                                                ]
                                            ],
                                        "time": ["时间暂停"]
                                    },
                                    {
                                        "type": "替换模块",
                                        "model":
                                            [
                                                [
                                                    "OR-替换260S",
                                                    "OR-替换210S",
                                                    "OR-替换160S",
                                                    "OR-替换160R",
                                                    "OR-替换160E",
                                                    "OR-替换150S",
                                                    "OR-替换100S",
                                                    "OR-替换100R",
                                                    "OR-替换10R"
                                                ]
                                            ],
                                        "time": ["时间替换"]
                                    },
                                    {
                                        "type": "光纤转发器及模块",
                                        "model":
                                            [
                                                [
                                                    "OR-FC1400",
                                                    "OR-FC311A-20",
                                                    "OR-FC311B-20",
                                                    "OR-FC311A-3",
                                                    "OR-FC311B-3",
                                                    "OR-FC314B-20",
                                                    "OR-FC314B-3",
                                                    "OR-FC111A",
                                                    "OR-FC111B",
                                                    "OR-FC114B",
                                                    "OR-FC114PB",
                                                    "OR-MC210CS",
                                                    "OR-MC200CM",
                                                    "OR-SM531LS",
                                                    "OR-SM531LM",
                                                    "OR-SM311LS",
                                                    "OR-SM311LM",
                                                    "TR-962D",
                                                    "TR-932D"
                                                ]
                                            ],
                                        "time": ["时间替换"]
                                    },
                                    {
                                        "type": "JHJ配件",
                                        "model":
                                            [
                                                [
                                                    "OR-RPS150",
                                                    "OR-EM532",
                                                    "OR-TC532-3",
                                                    "OR-TC532-1"
                                                ]
                                            ],
                                        "time": ["时间替换"]
                                    }
                                ]
                    },
                    {
                        "name": "WK",
                        "detail":
                                [
                                    {
                                        "type": "有炬PCIWK",
                                        "model":
                                            [
                                                [
                                                    "TG-3269E",
                                                    "TG-3269C",
                                                    "TF-3239DL"
                                                ]
                                            ],
                                        "time": ["时间暂停"]
                                    },
                                    {
                                        "type": "N炬USBWK",
                                        "model":
                                            [
                                                [
                                                    "OR-RIW7200H",
                                                    "OR-RIW6200H免驱",
                                                    "OR-RIW6200H",
                                                    "OR-RIW6200",
                                                    "OR-RIW5200H免驱",
                                                    "OR-RIW5200H",
                                                    "OR-RIW5200免驱",
                                                    "OR-RIW5200",
                                                    "OR-RI826N免驱",
                                                    "OR-RI826N",
                                                    "OR-RI823N",
                                                    "OR-RI821N",
                                                    "OR-RI822N",
                                                    "OR-RI726N免驱",
                                                    "OR-RI726N",
                                                    "OR-RI725N免驱",
                                                    "OR-RI725N"
                                                ]
                                            ],
                                        "time": ["时间暂停"]
                                    },
                                    {
                                        "type": "N炬PCIWK",
                                        "model":
                                            [
                                                [
                                                    "OR-RIW8280",
                                                    "OR-RIW7280",
                                                    "OR-RIW6280",
                                                    "OR-RIW5280",
                                                    "OR-RIW4800",
                                                    "OR-RI881N",
                                                    "OR-RI851N",
                                                    "OR-RI781N"
                                                ]
                                            ],
                                        "time": ["时间暂停"]
                                    },
                                    {
                                        "type": "USB转网口适配器",
                                        "model":
                                            [
                                                [
                                                    "OR-UF210红、绿"
                                                ]
                                            ],
                                        "time": ["时间暂停"]
                                    }
                                ]
                    },
                    {
                        "name": "其他设备",
                        "detail":
                                [
                                    {
                                        "type": "开氏温标",
                                        "model":
                                            [
                                                [
                                                    "OR-CD410",
                                                    "OR-CD310",
                                                    "OR-CD200",
                                                    "OR-CD100"
                                                ]
                                            ],
                                        "time": ["时间替换"]
                                    },
                                    {
                                        "type": "东方今典",
                                        "model":
                                            [
                                                [
                                                    "OR-RC1",
                                                    "OR-IPC30"
                                                ]
                                            ],
                                        "time": ["时间替换"]
                                    },
                                    {
                                        "type": "络硬萨满",
                                        "model":
                                            [
                                                [
                                                    "TD-W89941N增强型",
                                                    "TD-W89841N增强型",
                                                    "TD-W89741N增强型",
                                                    "TD-8620增强型",
                                                    "TD-8620T白、黑",
                                                    "OR-EP530",
                                                    "OR-EP110",
                                                    "OR-GP530",
                                                    "OR-GP110",
                                                    "OR-WA850N",
                                                    "OR-WA750N"
                                                ]
                                            ],
                                        "time": ["时间暂停"]
                                    },
                                    {
                                        "type": "打印服务器",
                                        "model":
                                            [
                                                [
                                                    "OR-WPS510U",
                                                    "OR-PS110P",
                                                    "OR-PS110U"
                                                ]
                                            ],
                                        "time": ["时间替换"]
                                    }
                                ]
                    },
                    {
                        "name": "络硬萨满设备",
                        "detail":
                                [
                                    {
                                        "type": "络硬萨满",
                                        "model":
                                            [
                                                [
                                                    "OR-IPC555",
                                                    "OR-IPC553",
                                                    "OR-IPC545",
                                                    "OR-IPC543",
                                                    "OR-IPC535KP",
                                                    "OR-IPC535K",
                                                    "OR-IPC535P",
                                                    "OR-IPC535",
                                                    "OR-IPC533KP",
                                                    "OR-IPC533K",
                                                    "OR-IPC533P",
                                                    "OR-IPC533",
                                                    "OR-IPC525KP",
                                                    "OR-IPC525K",
                                                    "OR-IPC525P",
                                                    "OR-IPC525",
                                                    "OR-IPC523KP",
                                                    "OR-IPC523K",
                                                    "OR-IPC523P",
                                                    "OR-IPC523",
                                                    "OR-IPC453P",
                                                    "OR-IPC453",
                                                    "OR-IPC433P",
                                                    "OR-IPC433",
                                                    "OR-IPC423P",
                                                    "OR-IPC423"
                                                ]
                                            ],
                                        "time": ["时间替换"]
                                    },
                                    {
                                        "type": "络硬萨满",
                                        "model":
                                            [
                                                [
                                                    "OR-AP301V-223",
                                                    "OR-IPC30",
                                                    "OR-IPC22-4",
                                                    "OR-IPC20A",
                                                    "OR-IPC20-2.8",
                                                    "OR-IPC10A",
                                                    "OR-IPC355",
                                                    "OR-IPC353",
                                                    "OR-IPC333K",
                                                    "OR-IPC325KP",
                                                    "OR-IPC325K",
                                                    "OR-IPC325P",
                                                    "OR-IPC325",
                                                    "OR-IPC323K-4-W10",
                                                    "OR-IPC323P",
                                                    "OR-IPC323",
                                                    "OR-IPC315KP",
                                                    "OR-IPC315K",
                                                    "OR-IPC315P",
                                                    "OR-IPC315",
                                                    "OR-IPC313KP",
                                                    "OR-IPC313K",
                                                    "OR-IPC313P",
                                                    "OR-IPC313",
                                                    "OR-IPC305KP",
                                                    "OR-IPC305K",
                                                    "OR-IPC305P",
                                                    "OR-IPC305",
                                                    "OR-IPC303KP",
                                                    "OR-IPC303K",
                                                    "OR-IPC303P",
                                                    "OR-IPC303",
                                                    "OR-IPC223K",
                                                    "OR-IPC223P",
                                                    "OR-IPC223",
                                                    "OR-IPC213K",
                                                    "OR-IPC213P",
                                                    "OR-IPC213",
                                                    "OR-IPC203K",
                                                    "OR-IPC203P",
                                                    "OR-IPC203"
                                                ]
                                            ],
                                        "time": ["时间替换"]
                                    },
                                    {
                                        "type": "络硬萨满",
                                        "model":
                                            [
                                                [
                                                    "OR-NVR6432",
                                                    "OR-NVR6232",
                                                    "OR-NVR6216",
                                                    "OR-NVR6108P",
                                                    "OR-NVR6108",
                                                    "OR-NVR6104P",
                                                    "OR-NVR6104"
                                                ]
                                            ],
                                        "time": ["两年替换"]
                                    },
                                    {
                                        "type": "络硬萨满",
                                        "model":
                                            [
                                                [
                                                    "OR-NVR5104S-KT30",
                                                    "OR-NVR5232",
                                                    "OR-NVR5216",
                                                    "OR-NVR5116",
                                                    "OR-NVR5108PE",
                                                    "OR-NVR5108P",
                                                    "OR-NVR5108K",
                                                    "OR-NVR5108",
                                                    "OR-NVR5104K",
                                                    "OR-NVR5104P",
                                                    "OR-NVR5104"
                                                ]
                                            ],
                                        "time": ["两年替换"]
                                    }
                                ]
                    }]